# Generated by Django 5.0.4 on 2024-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_Restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
