# Generated by Django 4.1 on 2024-04-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        ('maps', '0002_rename_locations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='itineraryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itinerary.useritinerary'),
        ),
    ]
