# Generated by Django 5.0.4 on 2024-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location_lat_location_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
