# Generated by Django 4.1 on 2024-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telephone'),
        ),
    ]
