# Generated by Django 5.0.4 on 2024-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritinerary',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useritinerary',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
