# Generated by Django 4.1 on 2024-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritinerary',
            name='rank',
        ),
        migrations.AddField(
            model_name='useritinerary',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
