# Generated by Django 5.0.4 on 2024-04-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_useritinerary_created_at_useritinerary_updated_at'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritinerary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.userprofile'),
            preserve_default=False,
        ),
    ]
